### ISSUE TITLE
have an error when i try to load the page 

### ISSUE THREAD

**Issue by ysus** [ngx-universal/translate-loader#1]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => check the README and search github for a similar issue or PR before submitting
[x ] support request => check the README and search github for a similar issue or PR before submitting
[ ] feature request
```

**Current behavior**

i have a error when i try to get the page
**Expected/desired behavior**

translate the content
**Minimal reproduction of the problem with instructions**

ERROR { TypeError: r.i(...) is not a function
    at Observable._subscribe (C:\src\webapp-intertours\node_modules\@ngx-universal\translate-loader\bundles\translate-loader.umd.min.js:1:5507)
    at Observable._trySubscribe (C:\src\webapp-intertours\node_modules\rxjs\Observable.js:57:25)
    at Observable.subscribe (C:\src\webapp-intertours\node_modules\rxjs\Observable.js:45:27)
    at Observable.ConnectableObservable.connect (C:\src\webapp-intertours\node_modules\rxjs\observable\ConnectableObservable.js:37:18)
    at RefCountOperator.call (C:\src\webapp-intertours\node_modules\rxjs\observable\ConnectableObservable.js:103:49)
    at Observable.subscribe (C:\src\webapp-intertours\node_modules\rxjs\Observable.js:42:22)
    at TakeOperator.call (C:\src\webapp-intertours\node_modules\rxjs\operator\take.js:60:23)
    at Observable.subscribe (C:\src\webapp-intertours\node_modules\rxjs\Observable.js:42:22)
    at TranslateService.getTranslation (C:\src\webapp-intertours\dist\server.js:497:14)
    at TranslateService.retrieveTranslations (C:\src\webapp-intertours\dist\server.js:482:87)
    at TranslateService.setDefaultLang (C:\src\webapp-intertours\dist\server.js:427:28)
    at new AppComponent (C:\src\webapp-intertours\dist\server.js:11426:19)
    at createClass (C:\src\webapp-intertours\node_modules\@angular\core\bundles\core.umd.js:10801:26)
    at createDirectiveInstance (C:\src\webapp-intertours\node_modules\@angular\core\bundles\core.umd.js:10627:37)
**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebVi.2ew ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
* **Node (for AoT issues):** `node --version` =  >6

**Comment by adebree** [comment]
Can confirm, having the same issue / error in a Angular 4.1.3 application.

**Comment by ysus** [comment]
it works now thks

**Comment by fulls1z3** [comment]
Hi @ysus sorry for late reply, could you please provide more details about how it got solved? Did you upgrade Angular or rxjs? This information would be very helpful for further maintenance. Thanks.

**Comment by ysus** [comment]
when i started my project i used this repo :
https://github.com/evertonrobertoauler/universal-demo
but only run when i change r.i(...) inside  translate-loader.umd.min.js for this line `require('fs').readFileSync("./dist/" + t.prefix + "/" + e + t.suffix, "utf8")` but with this repo i have another problems like don´t  render the http calls.

This week change for this repo https://github.com/FrozenPandaz/ng-universal-demo and all your libs ngx work fine with any change

**Comment by matochu** [comment]
Have the same issue with angular-cli v1.3rc3 and angular 4.3.3

**Comment by fulls1z3** [comment]
@ysus @adebree @allfayn are we talking about **ngx-translate** `v6.x` or `v7.x`?

**Comment by matochu** [comment]
@fulls1z3 ngx-translate/core v7.1.0

**Comment by matochu** [comment]
@fulls1z3 ngx-translate/core v6.0.1 same problem

**Comment by Norbert1001001** [comment]
I am running into the same issue. Trying to get ngx-translate to work with universal using ngx-universal/translate-loader. It compiles fine but when I run it, I get the same error on the server side: r.i(...) is not a function. 

My setup goes with those versions:
angular/cli@1.3.1
angular/core@4.3.5
ngx-translate/core@6.0.1
ngx-universal/translate-loader@0.4.0-beta.1

It happens on the function translate.use() from TranslateService and only on server side. 

EDIT SOLVED: I forgot to put ngx-universal\/translate-loader into the externals in webpack.config.js just like I did with ngx-translate\/core, that's why I was getting the error. Now it works fine.

**Comment by ysus** [comment]
i use this repo:
[https://github.com/FrozenPandaz/ng-universal-demo](https://github.com/FrozenPandaz/ng-universal-demo)and works perfect this is my configuration:

![sss](https://user-images.githubusercontent.com/14302557/30034475-50a7a8d2-9167-11e7-84ad-dc5449fd75f6.png)
